### ISSUE TITLE
@adeira/relay: Fragment definitions should be regenerated after migration

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#153]
Migrating from `react-relay` to `@adeira/relay` doesn't regenerate files if fragment definitions are the same as before.

This might cause confusion especially for flow as old fragments import type from the untyped library:

```
import type { ConcreteRequest } from 'relay-runtime';
```

Conclusion:
- files should be regenerated

or

- this limitation documented

**Comment by mrtnzlml** [comment]
`@adeira/relay` is not freely interchangeable with Relay packages (and we do not advertise it like this, I hope). Moreover, this is not easily fixable and I do not think we should document it (since there is nothing about migration anywhere if I recall correctly).

However, feel free to send a PR to the docs if you disagree with my statement above. :)

**Comment by jaroslav-kubicek** [comment]
ok, I agree with your point, we should probably have some description of what to do if you want to to start using `@adeira/relay` while you are on `react-relay`, sounds reasonable?

**Comment by mrtnzlml** [comment]
Yes, there could be some short section with this info. I wouldn't go into details very much though - maybe just to describe what's different (which is constantly changing).
