### ISSUE TITLE
@adeira/relay: Document what to do when migrating from react-relay lib

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#154]
Based on issues  https://github.com/adeira/universe/issues/153 & https://github.com/adeira/universe/issues/151 we should have brief guideline what do to & what can happen when replacing `react-relay` by `@adeira/relay`

- how to set `.flowconfig`
- fragments should be regenerated

**Comment by mrtnzlml** [comment]
BTW this is a bit tricky business because both issues were about generated files but you cannot be sure what files are users generating and how. It's because this is up to the developers (you can change the so-called [language plugin](https://github.com/facebook/relay/tree/f66ee5cc5968ac585de28057c86fa73659bbc46c/packages/relay-compiler/language) which some people do). It would be nice to take it into account.

**Comment by michalsanger** [comment]
@jaroslav-kubicek please reopen if you still think this is an issue
