### ISSUE TITLE
@adeira/eslint-plugin: Introduce new rule for better GraphQL server

### ISSUE THREAD

**Issue by jaroslav-kubicek** [adeira/universe#210]
when implementing GraphQL server, I suggest to check that every instance of  `GraphQLObjectType` satisfies following rules:

- has a description
- name matching the filename

**Comment by mrtnzlml** [comment]
One year! Happy birthday! 🎂 😊 

I would like to close this issue as it is being stale and we were not able to fix it in a reasonable time. It could be due to insufficient resources from our side or we simply do not consider it to be a big deal.

Here are some options what to do now:

1. You can send a pull request if you consider the issue to be important for you and you'd like to contribute back. ✍️ 
1. You can consider sponsoring one of our maintainers to help us deal with the associated maintenance and development costs. It will be greatly appreciated. 👍 
1. You can fork our open-source projects and start developing your own version. Consider contributing back first though.
1. Do nothing.

Thanks for understanding. ❤️
