### ISSUE TITLE
Switch to the new flow eslint plugin

### ISSUE THREAD

**Issue by maicol07** [adeira/universe#3609]
Recently, a  new eslint plugin for flow has been released: [https://github.com/flow-typed/eslint-plugin-ft-flow](https://github.com/flow-typed/eslint-plugin-ft-flow)

It contains all the rules of the previous, unofficial plugin and has some new ones.

I think the adeira eslint config should switch to the new plugin.

**Comment by mrtnzlml** [comment]
Hi @maicol07, thanks for the issue! 👍 I've noticed this new repository/release a few days ago. Would you like to send a pull request to this repository to change it? I can navigate you if needed. 😊

Cc @Brianzchen: I agree that the original plugin definitely needs a lot of work and updates. My concern is: aren't we just switching from a one-man show to another one-man show with possibly the same result? 🤔 Just asking.

I am also offering to merge it under [`adeira/universe`](https://github.com/adeira/universe) monorepo to keep it going. The whole monorepo uses Flow and there are no plans to change it. Feel free to get in touch with me in case you'd be interested to know more. We have more people who can help with code reviews and merging PRs more quickly. 😎 

Related issue: https://github.com/gajus/eslint-plugin-flowtype/issues/462

**Comment by maicol07** [comment]
@mrtnzlml are there some of the new rules that needs to be configured or toggled off like the other ones?

**Comment by Brianzchen** [comment]
Hey thanks for tagging me. So here's the story, the original eslint-pugin-flowtype didn't get maintained with broken tests and prs/issues that were uncared for, I worried that this would hurt the flowtype community given interested parties tried to help build news rules but get ultimately shut down through the a lack of response. Since I'm part of the flow-typed org I thought why not publish my own version under that org.

I even asked in the issue above with no reply so I assume it's now fair game in the open source world.

> aren't we just switching from a one-man show to another one-man show with possibly the same result? 

I'd say maybe, though in the end I'd say at least my guarantee is that you'll get a faster reply from me given I don't really maintain very much and I'm interested in using flow for my personal projects so I'll have motivation to maintain and add improvements where I see fit. Otherwise I leave it to the community to contribute.

I've also maintenance rights to @angelica-bocanegra who I know personally and has made some nice contributions to the previous repo in the past year. So maybe one man + one lady :joy:

**Comment by mrtnzlml** [comment]
@maicol07 Do you know what are the new rules? The process of adding new rules is usually this:

- we run `yarn test-only src/eslint-config-adeira` and see what new rules are missing (everything is snapshotted)
- we decide whether the rules are useful based on the rule docs and enable them via `NEXT_VERSION_ERROR` constant (we avoid opinionated/annoying/broken rules)
- we run `yarn lint --all` to see how it works for `adeira/universe` (if there are too many errors we disable it and decide what to do next - for example, create a follow-up issue to fix the errors first and enable the rule later)

I can help you to make the decision about the newly added rules (based on some initial PR).

**Comment by Brianzchen** [comment]
> @maicol07 Do you know what are the new rules?

Should be just these
https://github.com/flow-typed/eslint-plugin-ft-flow/pull/5
https://github.com/flow-typed/eslint-plugin-ft-flow/pull/2
https://github.com/flow-typed/eslint-plugin-ft-flow/pull/3

**Comment by mrtnzlml** [comment]
> > @maicol07 Do you know what are the new rules?
> 
> Should be just these
> [flow-typed/eslint-plugin-ft-flow#5](https://github.com/flow-typed/eslint-plugin-ft-flow/pull/5)
> [flow-typed/eslint-plugin-ft-flow#2](https://github.com/flow-typed/eslint-plugin-ft-flow/pull/2)
> [flow-typed/eslint-plugin-ft-flow#3](https://github.com/flow-typed/eslint-plugin-ft-flow/pull/3)

👍

Pretty sure the first two (flow enums and suppression code enforcement) should be enabled with `NEXT_VERSION_ERROR`. The last one ideally as well but I would expect some issues in our code in which case I'd suggest to disable it for now `OFF` and create a follow-up issue to fix the code and enable the rule again (fix the code probably means only to switch some files from `@flow strict` to `@flow`).

**Comment by mrtnzlml** [comment]
I am going to fix this issue. Seems like there are more rules that were previously not enabled and it requires a bit of knowledge of `adeira/universe`.

**Comment by mrtnzlml** [comment]
Here we go: https://github.com/adeira/universe/pull/3612

Unfortunately, there are some issues that prevent me from enabling all the rules (so I basically only switched the plugin and disabled the new rules for now). It doesn't mean I am not going to enable the new rules. It just means that I will do it later once the other things and bugs get resolved. 😊
