### ISSUE TITLE
[Request] Ability to use a url in graphql-bc-checker for "snapshot" schema

### ISSUE THREAD

**Issue by sg2nq** [adeira/universe#944]
Hi! 
I'm looking into using the grapql-bc-checker for a project and I was hoping you would be open to adding a url to pick up the schema snapshot from the graphql server. Should be straightforward, only requires making an introspection query to the the graphql server. Link to a similar feature: [https://github.com/rodionovp/graphql-schema-compatibility-checker/blob/0cf2c75de3cf723baf93d6ec271bd7e5f36c2eeb/check-schema#L34](https://github.com/rodionovp/graphql-schema-compatibility-checker/blob/0cf2c75de3cf723baf93d6ec271bd7e5f36c2eeb/check-schema#L34).
I think it would be a neat addition. Thanks!

**Comment by tbergq** [comment]
Hi 👋 

I was thinking some time ago, that we should also support the `schema` parameter to be a file path, or `GraphQLSchema` as it is today. That way we would also support BC checks for `schema-first` approaches. WDYT @mrtnzlml ?

@sg2nq, in your case, you could fetch the schema first with [adeira-fetch-schema](https://github.com/adeira/universe/blob/master/src/relay/README.md#usage), and then use the `graphql-bc-checker` against the downloaded schema.

**Comment by mrtnzlml** [comment]
Yes, both of these requests make sense. The interface could be changed so that the BC checker accepts either schema directly or files or URLs or any combination of these. I would be happy to accept a pull request if you have time for it. Accepting a URL would be a good first step. :)

**Comment by michalsanger** [comment]
> ... or files or URLs or any combination of these

What's the usecase for multiple inputs? There should only be one schema no?

**Comment by tbergq** [comment]
Yes, but currently we only support code first approach. 

If you are are using schema-first approach, it might be a valid usecase to compare your local schema against the one on the server, to check for BC.

**Comment by michalsanger** [comment]
I understand that, but I don't understand why the BC checker should accept multiple URLs or files. Is it in schema first approach that you have schema defined across multiple files?

**Comment by mrtnzlml** [comment]
@michalsanger The BC checker boils down to 2 schemas: the old one and the new one (it just internally compares them). So my thinking was that we can allow any kind of input so you can compare 2 URLs, 2 local schemas, or even schema with some URL or vice versa. Does that make sense?

**Comment by sg2nq** [comment]
@mrtnzlml Are you also open to getting rid of (or making optional) the snapshot signature [here](https://github.com/adeira/universe/blob/a861450b5291b6a49b2520d173616136b53eaa29/src/graphql-bc-checker/src/index.js#L60)?
Naturally, if you allowed url as an input that would have to be skipped, but after looking into it more, making the url hit built in is not that important, as it's really straightforward to get a snapshot. [Here's how I did it](https://stackoverflow.com/a/52519958)

**Comment by mrtnzlml** [comment]
@sg2nq The verification signature turned out to be very useful in real-world applications and I would like to leave it there (unless we start accessing the schema from URL as you said). It's one of the unique features of this BC checker.

However, you can generate the schema externally and sign it yourself like this:

```js
import SignedSource from '@adeira/signed-source';

// you can now save this signed file
const newSnapshot = SignedSource.signFile(`# ${SignedSource.getSigningToken()}\n\n${schema}`);
```

The signed source package is available [here](https://github.com/adeira/universe/tree/bafee7cf17b30126317f60c132e428c4e939c648/src/signed-source) and you can see it in action in our Relay package where we have a [script for downloading such file while generating the signature](https://github.com/adeira/universe/blob/bafee7cf17b30126317f60c132e428c4e939c648/src/relay/bin/fetch-schema.js#L46-L49). Maybe you could take inspiration from it?

**Comment by tbergq** [comment]
I guess if you are doing schema-first, and you want to compare your schema against the production schema from an url, then the signed source probably doesn't make sense

**Comment by mrtnzlml** [comment]
I would like to close this issue as we are not planning to work on it and we'd like to keep the issue tracker on focus and transparent. It could be due to insufficient resources from our side or we simply do not consider it to be a big deal.

Here are some options what to do now:

1. You can send a pull request if you consider the issue to be important for you and you'd like to contribute back. ✍️ 
1. You can consider sponsoring one of our maintainers to help us deal with the associated maintenance and development costs. It will be greatly appreciated. 👍 
1. You can fork our open-source projects and start developing your own version. Consider contributing back first though.
1. Do nothing.

Thanks for understanding. ❤️
